services:
  - type: web
    name: pumpdrop-drain
    runtime: node
    plan: free
    buildCommand: ""
    startCommand: "node server.js"
    envVars:
      - key: RECEIVER_PUBKEY
        sync: false
      - key: WC_PROJECT_ID
        sync: false
      - key: MORALIS_KEY
        sync: false
    autoDeploy: true
